# Generated by Django 5.2.6 on 2025-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='商户名称')),
                ('license_no', models.CharField(blank=True, max_length=100, verbose_name='营业执照号')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '正常'), ('suspended', '已冻结')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
                'ordering': ['-created_at'],
            },
        ),
    ]
