# Generated by Django 5.2.6 on 2025-09-24 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchant",
            options={
                "ordering": ["-register_time"],
                "verbose_name": "商户",
                "verbose_name_plural": "商户",
            },
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="license_no",
        ),
        migrations.AddField(
            model_name="merchant",
            name="account",
            field=models.CharField(
                help_text="邮箱或手机号",
                max_length=128,
                null=True,
                verbose_name="注册账号",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="accounts_applied",
            field=models.PositiveIntegerField(default=0, verbose_name="已申请账号数"),
        ),
        migrations.AddField(
            model_name="merchant",
            name="accounts_apply_limit",
            field=models.PositiveIntegerField(default=0, verbose_name="可申请账号数"),
        ),
        migrations.AddField(
            model_name="merchant",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("none", "未认证"),
                    ("personal", "个人认证"),
                    ("enterprise", "企业认证"),
                ],
                default="none",
                max_length=16,
                verbose_name="认证类型",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="comments",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="merchant",
            name="distributor",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="所属分销/渠道"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="last_eval_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近评估时间"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="merchants.merchant",
                verbose_name="所属上级",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="region",
            field=models.CharField(
                choices=[("cn", "中国大陆"), ("hk", "中国香港")],
                max_length=64,
                null=True,
                verbose_name="注册地区",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="register_time",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, null=True, verbose_name="注册时间"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "低风险"),
                    ("medium", "中风险"),
                    ("high", "高风险"),
                    ("na", "暂无评估"),
                ],
                default="na",
                max_length=16,
                verbose_name="风险等级",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="id",
            field=models.CharField(
                db_index=True,
                max_length=32,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="商户编号",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="商户名称"
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="status",
            field=models.CharField(
                choices=[
                    ("enabled", "活动"),
                    ("disabled", "冻结"),
                    ("deleted", "注销"),
                    ("INACTIVE", "休眠"),
                ],
                default="disabled",
                max_length=16,
                verbose_name="商户状态",
            ),
        ),
    ]
